language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodrigofbm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t rodrigofbm/multi-client -f ./client
  - docker build -t rodrigofbm/multi-nginx -f ./nginx
  - docker build -t rodrigofbm/multi-server -f ./server
  - docker build -t rodrigofbm/multi-worker -f ./worker


