language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodrigofbm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodrigofbm/react-test npm test

after_success:
  - docker build -t rodrigofbm/multi-client -f ./client
  - docker build -t rodrigofbm/multi-nginx -f ./nginx
  - docker build -t rodrigofbm/multi-server -f ./server
  - docker build -t rodrigofbm/multi-worker -f ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rodrigofbm/multi-client
  - docker push rodrigofbm/multi-nginx
  - docker push rodrigofbm/multi-server
  - docker push rodrigofbm/multi-worker

